all: ptrace_virt ptrace_virt_gsi ptrace_virt_ssi

ptrace_virt: ptrace_virt.c

ptrace_virt_gsi: ptrace_virt_gsi.c

ptrace_virt_ssi: ptrace_virt_ssi.c

clean:
	rm -f ptrace_virt ptrace_virt_gsi ptrace_virt_ssi
